import { writeFileSync } from "node:fs";

import { b, BARS, CUE, DURATION, GRID, SFX } from "../src/videos/gumroad/cues";

/**
 * Exports the cues for the music script, and the beat sheet for people.
 *
 *   bun scripts/cues-json.ts out/cues.json [beat-sheet.md]
 */
const [json, sheet] = process.argv.slice(2);
writeFileSync(json, JSON.stringify({ bpm: GRID.bpm, bars: BARS, duration: DURATION, sfx: SFX }, null, 2));

if (sheet) {
  const where = (seconds: number) => {
    const beats = seconds / (60 / GRID.bpm);
    const bar = Math.floor(beats / 4) + 1;
    const beat = beats - (bar - 1) * 4 + 1;
    return `${bar}.${Number.isInteger(beat) ? beat : beat.toFixed(1)}`;
  };
  const rows = Object.entries(CUE).map(([name, at]) => `| ${where(at)} | ${at.toFixed(3)} s | ${Math.round(at * 60)} | ${name} |`);
  writeFileSync(sheet, [`# Beat sheet: Gumroad ad (${GRID.bpm} BPM, ${BARS} bars, ${DURATION.toFixed(1)} s)`, "", "Generated by `scripts/cues-json.ts` from `src/videos/gumroad/cues.ts`.", "", "| Bar.beat | Time | Frame @60 | Cue |", "|---|---|---|---|", ...rows, `| ${BARS + 1}.1 | ${b(BARS + 1).toFixed(3)} s | ${Math.round(DURATION * 60)} | end |`, ""].join("\n"));
}
